FROM ubuntu:latest
WORKDIR /app
RUN apt update
RUN apt install -y nodejs
RUN apt install -y npm
RUN npm install -y live-server
COPY index.html /app
EXPOSE 5050
CMD ["npx","live-server", "index.html","--port=5050"]